config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "todos#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :todo
  
end

app/models/todo.rb
class Todo < ApplicationRecord
    has_many :tasks, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    def show
        @task = Task.find(params[:id])
        @task = Task.all
     
         
    end

    def create
        @task = Task.create(task_params)
        if @task.save
            redirect_to todo_path(@task.todo_id), notice: "Task was successfully created." 

        else
            redirect_to root_path
        end
    end

    def update
        @task = Task.find(params[:id])
        @task.update(task_params)
        redirect_to todo_path(@task.todo_id), notice: "Task was successfully updated."

    end

    def edit 
        @task = Task.find(params[:id])        
    end

    def destroy
        @task = Task.find(params[:id])
        @task.destroy         
        respond_to do |format|
            format.html { redirect_to todo_path, notice: "Task was successfully destroyed." }
            format.json { head :no_content }
        end
        

    end
    
    private
    def task_params
        params.require(:task).permit(:title, :done, :todo_id)
    end


end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    if params[:search]
      search_todo
    end
    @todos = Todo.all
    @todo = Todo.new
  end

  # GET /todos/1 or /todos/1.json
  def show
    @task = Task.new
    @tasks = @todo.tasks
    @todo = Todo.find(params[:id])
    
  end

  def search_todo

    if @todo = Todo.all.find{|todo| todo.name.include?(params[:search])}
      redirect_to todo_path(@todo)
    end
  end


  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
   
  end

  

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to root_path, notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:name, :progress)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <meta http-equiv= "X-UA-Compatible" content="ie=edge">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <header>
    <p>Developed by Cristian Santiago - &copy; <%= Date.current.year %></p>
  </header>
  <body>
     
   
    <%= yield %>

  </body>
</html>

app/views/tasks/_edit.html.erb
<section class="vh-150 py-5">
  <div class="container py-5 h-100" id="container">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-9">
        <div class="card rounded-3 transparent">
          <div class="card-body p-4">
            <h1 class="text-center my-3 pb-3">Editing Task</h1>
              <%= form_with model: @task do |form| %>
                <div>
                  <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
                    <div class="col-12">                        
                      <div class="form-outline">                                                      
                        <p><%= form.text_field :title, maxlength: 200, required: true, placeholder:"Edit Task", class: "form-control"%></p>                                                      
                      </div>
                    </div>
                    <div >
                      <%= button_to "Update", @task, method: :edit , class: "btn btn-success " %>
                      <%= link_to "Return",todo_path(@task.todo_id), required: false, class: "link btn btn-secondary button-back" %>
                      <p style="color: green"><%= notice %></p>         
                    </div>                    
                  </form>  
                </div>
              <% end %>   
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/tasks/edit.html.erb
<%= render 'edit' %>

app/views/todos/_form.html.erb
<section class="vh-150  py-5 " >
  <div class="container py-5 h-100 " >
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-9">
        <div class="card rounded-3 transparent">
          <div class="card-body p-4 ">
            <h1 class="text-center my-3 pb-3">To Do App</h1>
              <%= form_with(model: @todo) do |form| %>
                <div>
                  <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
                    <div class="col-12">                        
                      <div class="form-outline">                                                      
                        <p><%= form.text_field :name, maxlength: 45, required: true, placeholder:"Create a main task here", class: "form-control "%></p>                                                      
                      </div>
                    </div>
                    <div >
                      <%= button_to "Create", @todo, method: :new, class: "btn btn-success " %> 
                      <p style="color: green"><%= notice %></p>         
                    </div>
                    <div class="form-outline mb-4">                        
                      <%= form_tag(@todos_paths, method: :get) do %>
                        <p><%= text_field_tag(:search, params[:search], placeholder: "Search for a main task here.", class: "form-control") %></p>
                        <%= submit_tag("Search",  class: "btn btn-primary")%>
                      <%end%>
                    </div>
                  </form>  
                </div>
              <% end %>
            <div class="table-responsive">                                  
              <table class=" table mb-1 col col-lg-9">
                <thead>
                  <tr>                  
                    <th scope="col">Todo item</th>                    
                    
                  </tr>
                </thead>
                <tbody>                  
                    <% @todos.each do |todo| %>
                      <tr>                        
                        <th scope="row" class="col col-lg-9">
                          <p class="margin-p" ><%= link_to todo.name, todo, class: "todo-link" %></p>
                        </th>  
                        <td >                                            
                            <%= link_to "Edit", edit_todo_path(todo), class: "link btn btn-warning " %>
                        <td >                       
                        <td >                        
                            <%= button_to "Delete", todo, method: :delete, class: "btn btn-danger" %> 
                        </td>  

                      </tr>
                    <%end%>                
                </tbody>
              </table>
             </div> 
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/todos/_todo.html.erb
<section class="vh-150 py-5">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-9">
        <div class="card rounded-3 transparent">
          <div class="card-body p-4">
            <h1 class="text-center my-3 pb-3"> <%= @todo.name %> </h1>
              <%= form_for @task do |f| %>
                <div>
                  <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
                    <div class="col-12">
                      <div class="form-outline">
                        <p><%= f.text_field :title, maxlength: 200, required: true, placeholder: "Create tasks here", class: "form-control" %></p>
                          <%= f.hidden_field :todo_id, :value => @todo.id %>
                      </div>
                    </div>
                    <div>
                        <%= button_to "Create Task", @task, method: :new, class: "btn btn-success " %>                                
                        <%= link_to "Back Todo", todos_path, class: "link btn btn-secondary button-back" %>                        
                        <p style="color: green"><%= notice %></p>         
                    </div>
                  </form>  
                </div>
              <%end%>
            <div class="table-responsive">  
              <table class="table mb-1 col col-lg-9 ">
                <thead>
                  <tr>                    
                    <th scope="col">Todo item</th>                  
                    
                  </tr>
                </thead>             
                <tbody>
                  <% @tasks.each do |task| %> 
                    <tr>
                      <th scope = "row" class=" vertical-middle-txt col col-lg-9">
                        <p class="margin-p break-line"><%= task.title %></p>
                      </th>
                      <td class="button-inline-middle" >                                            
                          <%= link_to "Edit", edit_task_path(task), class: "link btn btn-warning" %>
                      <td>                       
                      <td class="button-inline-middle" >                        
                          <%= button_to "Delete", task, method: :delete, class: "btn btn-danger" %> 
                      </td>                 
                    </tr>
                  <% end %>                  
                </tbody>
              </table>
            </div>  
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/todos/edit.html.erb
<section class="vh-150 py-5">
  <div class="container py-5 h-100" id="container">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-9">
        <div class="card rounded-3 transparent">
          <div class="card-body p-4">
            <h1 class="text-center my-3 pb-3">Editing Todo</h1>
              <%= form_with(model: @todo) do |form| %>
                <div>
                  <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
                    <div class="col-12">                        
                      <div class="form-outline">                                                      
                        <p><%= form.text_field :name, maxlength: 45, required: true, placeholder:"Edit Todo", class: "form-control"%></p>                                                      
                      </div>
                    </div>
                    <div >
                      <%= button_to "Update", @todo, method: :edit, class: "btn btn-success " %>
                      <%= link_to "Show this Todo", @todo, required: false, class: "link btn btn-primary button-back" %>
                      <%= link_to "Back Todos", todos_path, required: false, class: "link btn btn-secondary button-back" %>
                      <p style="color: green"><%= notice %></p>         
                    </div>                    
                  </form>  
                </div>
              <% end %>   
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/todos/index.html.erb
<%= render 'form' %>

app/views/todos/show.html.erb
<%= render 'todo' %>